name: "publish web site :>"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  delpoy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: down load repo
        uses: actions/checkout@v4
      - name: down load npm
        run: |
          npm i -g sass typescript

      - name: gogol translaet tsc > js
        run: tsc
      - name: gogol translaet sass/scss > css
        run: sass .

      - name: upload artifac
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: publish site
        id: deployment
        uses: actions/deploy-pages@v4
