name: "publish web site :>"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  google_maps:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: down load
        uses: actions/checkout@v4
      - name: do some magic idk
        uses: actions/configure-pages@v5

      - name: transform hooman lagunage to compuper lamgusge
        run: tsc

      - name: upload among us
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: upload page (hooray)
        id: deployment
        uses: actions/deploy-pages@v4
